"""Validate or scaffold .env.

Modes:
  python scripts/ensure_env.py                              # validate only; exit 0 if ok
  python scripts/ensure_env.py --provider anthropic --key … # write .env from scratch
  python scripts/ensure_env.py --from-example               # copy .env.example → .env if missing

The skill router runs this in validate mode first; if it returns missing-key, the router asks
the user for a key and re-runs in write mode.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys

from _paths import ENV_EXAMPLE, ENV_FILE


PROVIDERS = {
    "anthropic": ("ANTHROPIC_API_KEY", "ANTHROPIC_MODEL", "claude-sonnet-4-6"),
    "openai":    ("OPENAI_API_KEY",    "OPENAI_MODEL",    "gpt-4o-mini"),
}


def _read_env() -> dict[str, str]:
    if not ENV_FILE.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV_FILE.read_text(encoding="utf-8", errors="ignore").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _validate() -> dict:
    env = _read_env()
    has_anthropic = bool(env.get("ANTHROPIC_API_KEY"))
    has_openai = bool(env.get("OPENAI_API_KEY"))
    if has_anthropic:
        return {"ok": True, "provider": "anthropic", "model": env.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")}
    if has_openai:
        return {"ok": True, "provider": "openai", "model": env.get("OPENAI_MODEL", "gpt-4o-mini")}
    return {"ok": False, "reason": "no provider key set in .env"}


def _write(provider: str, key: str, model: str | None) -> None:
    if provider not in PROVIDERS:
        raise SystemExit(f"unknown provider: {provider}; expected one of {list(PROVIDERS)}")
    key_var, model_var, default_model = PROVIDERS[provider]
    model = model or default_model

    lines = [
        "# Echo-Quill Alchemist .env  (auto-generated by scripts/ensure_env.py)",
        f"LLM_PROVIDER={provider}",
        f"{key_var}={key}",
        f"{model_var}={model}",
        "HOST=0.0.0.0",
        "PORT=8000",
        "",
    ]
    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"ok": True, "wrote": str(ENV_FILE), "provider": provider, "model": model}))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--provider", choices=list(PROVIDERS))
    ap.add_argument("--key")
    ap.add_argument("--model")
    ap.add_argument("--from-example", action="store_true",
                    help="copy .env.example → .env if .env is missing (still requires user to fill key)")
    args = ap.parse_args()

    if args.from_example:
        if ENV_FILE.exists():
            print(json.dumps({"ok": True, "note": ".env already exists; not overwritten"}))
            return 0
        if not ENV_EXAMPLE.exists():
            print(json.dumps({"ok": False, "reason": ".env.example missing"}))
            return 1
        shutil.copy2(ENV_EXAMPLE, ENV_FILE)
        print(json.dumps({"ok": True, "wrote": str(ENV_FILE), "from": str(ENV_EXAMPLE),
                          "note": "key still empty — fill before starting backend"}))
        return 0

    if args.provider and args.key:
        _write(args.provider, args.key, args.model)
        return 0

    # validate
    report = _validate()
    print(json.dumps(report, ensure_ascii=False))
    return 0 if report["ok"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
